const fs = require('fs');
let dbContent = fs.readFileSync('src/database/db.ts', 'utf8');

const regex = /const dummySagaRecords = \[[\s\S]*?\];\s*for \(const record of dummySagaRecords\) \{\s*await txn\.runAsync\(\s*`INSERT INTO saga_records \([\s\S]*?\) VALUES \([\s\S]*?\)`,\s*\[[\s\S]*?\],\s*\);\s*\}/;

const newStr = `const dummySagaRecords = [
            {
              child_id: 1,
              tanggal_pemeriksaan: date1Str,
              jam_pemeriksaan: "08:45",
              nama_anak: "Muhammad Zaki",
              umur_tahun: 1,
              umur_bulan: 8,
              berat_badan: 13.5,
              pb_tb: 88.0,
              gender: "Laki-laki",
              keluhan_utama: "Kejang dan kesulitan bernapas",
              answers: answers1,
              classification: "PENYAKIT_SANGAT_BERAT",
              status: "Perlu Perhatian",
              nik: "1234567890123456",
              alamat: "Jl. Merdeka No. 1, Jakarta",
              daerah_endemis_malaria: "TIDAK",
              rdt_malaria_result: "",
              lila: 14.5,
              lingkar_kepala: 45.0,
              suhu: 38.5,
              kunjungan_pertama: "YA",
              kunjungan_ulang: "TIDAK",
            },
            {
              child_id: 1,
              tanggal_pemeriksaan: date2Str,
              jam_pemeriksaan: "10:15",
              nama_anak: "Muhammad Zaki",
              umur_tahun: 1,
              umur_bulan: 8,
              berat_badan: 13.6,
              pb_tb: 88.5,
              gender: "Laki-laki",
              keluhan_utama: "Demam ringan",
              answers: answers2,
              classification: "STABIL",
              status: "Normal",
              nik: "1234567890123456",
              alamat: "Jl. Merdeka No. 1, Jakarta",
              daerah_endemis_malaria: "YA",
              rdt_malaria_result: "Positif",
              lila: 14.6,
              lingkar_kepala: 45.5,
              suhu: 37.0,
              kunjungan_pertama: "TIDAK",
              kunjungan_ulang: "YA",
            },
            {
              child_id: 1,
              tanggal_pemeriksaan: date3Str,
              jam_pemeriksaan: "09:30",
              nama_anak: "Muhammad Zaki",
              umur_tahun: 1,
              umur_bulan: 8,
              berat_badan: 13.7,
              pb_tb: 89.0,
              gender: "Laki-laki",
              keluhan_utama: "Kejang, sesak napas, dan pucat",
              answers: answers3,
              classification: "GAGAL_JANTUNG_PARU",
              status: "Kritis",
              nik: "1234567890123456",
              alamat: "Jl. Merdeka No. 1, Jakarta",
              daerah_endemis_malaria: "TIDAK",
              rdt_malaria_result: "",
              lila: 14.7,
              lingkar_kepala: 46.0,
              suhu: 39.2,
              kunjungan_pertama: "TIDAK",
              kunjungan_ulang: "YA",
            },
          ];

          for (const record of dummySagaRecords) {
            await txn.runAsync(
              \`INSERT INTO saga_records (
                child_id, tanggal_pemeriksaan, jam_pemeriksaan, nama_anak, 
                umur_tahun, umur_bulan, berat_badan, pb_tb, gender, keluhan_utama, 
                answers, classification, status, nik, alamat, daerah_endemis_malaria,
                rdt_malaria_result, lila, lingkar_kepala, suhu, kunjungan_pertama, kunjungan_ulang
              ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\`,
              [
                record.child_id,
                record.tanggal_pemeriksaan,
                record.jam_pemeriksaan,
                record.nama_anak,
                record.umur_tahun,
                record.umur_bulan,
                record.berat_badan,
                record.pb_tb,
                record.gender,
                record.keluhan_utama,
                record.answers,
                record.classification,
                record.status,
                record.nik,
                record.alamat,
                record.daerah_endemis_malaria,
                record.rdt_malaria_result,
                record.lila,
                record.lingkar_kepala,
                record.suhu,
                record.kunjungan_pertama,
                record.kunjungan_ulang,
              ],
            );
          }`;

dbContent = dbContent.replace(regex, newStr);
fs.writeFileSync('src/database/db.ts', dbContent);
console.log('Modified via regex');
